In [8]:
import pandas as pd
from sklearn.neighbors import KNeighborsClassifier
from sklearn.model_selection import train_test_split

data = pd.read_csv('Instruments.csv')
 
data.head()

data.iloc[:,1:52]
# Create feature and target arrays
X = data.iloc[:,1:52]
y = data['Actor']
# Split into training and test set
X_train, X_test, y_train, y_test = train_test_split(
             X, y, test_size = 0.2, random_state=42)
 
knn = KNeighborsClassifier(n_neighbors=7)
 
knn.fit(X_train, y_train)
 
# Predict on dataset which model has not seen before
y_predicted=knn.predict(X_test)

y_predicted

array(['Rajini', 'Viay', 'Rajini', 'Surya', 'Viay', 'Viay', 'Kamal',
       'VJS', 'D', 'Vikram', 'Ajith', 'Rajini', 'SK', 'Simbu', 'D', 'D',
       'Surya', 'SK', 'D', 'Surya', 'Viay', 'D', 'SK', 'Vikram', 'Viay',
       'Simbu', 'Ajith', 'Viay', 'VJS', 'Rajini', 'Ajith', 'Vikram',
       'Viay', 'Viay', 'Rajini', 'Simbu', 'Viay', 'Rajini', 'VJS', 'Viay',
       'Rajini', 'Viay', 'Viay', 'Ajith', 'D', 'Rajini', 'Ajith',
       'Rajini', 'Viay', 'Viay', 'Simbu', 'VJS', 'D', 'D', 'VJS', 'Kamal',
       'Kamal', 'Kamal', 'Viay', 'Kamal', 'Simbu', 'Ajith', 'Rajini',
       'Viay', 'Rajini', 'SK', 'Simbu', 'Ajith', 'Viay', 'Viay', 'VJS',
       'D', 'Viay', 'SK', 'Viay', 'Rajini', 'VJS', 'Ajith', 'VJS',
       'Simbu', 'D', 'Simbu', 'Kamal', 'Simbu', 'Rajini', 'VJS', 'D',
       'SK', 'Kamal', 'Ajith', 'Ajith', 'Ajith', 'Viay', 'Vikram', 'SK',
       'Surya', 'Rajini'], dtype=object)

In [8]:
data['Actor']

0           D
1           D
2           D
3           D
4           D
        ...
479    Vikram
480    Vikram
481    Vikram
482    Vikram
483    Vikram
Name: Actor, Length: 484, dtype: object

In [9]:
from sklearn.metrics import accuracy_score

accuracy_score(y_test,y_predicted)

0.18556701030927836

In [4]:
from sklearn.metrics import classification_report, confusion_matrix

print(confusion_matrix(y_test,y_predicted))
print('\n')
print(classification_report(y_test,y_predicted))

[[4 1 0 4 0 1 1 1 3 0]
 [1 1 1 1 1 1 0 1 2 0]
 [0 0 0 3 1 0 1 0 2 0]
 [0 1 0 4 0 2 0 1 1 0]
 [0 2 0 0 0 0 0 0 1 1]
 [1 2 1 0 0 2 0 0 2 0]
 [0 0 1 0 1 0 0 1 1 0]
 [0 2 2 2 2 1 0 3 1 1]
 [2 0 2 0 1 2 1 2 2 0]
 [3 2 0 0 1 0 1 0 6 2]]


              precision    recall  f1-score   support

       Ajith       0.36      0.27      0.31        15
           D       0.09      0.11      0.10         9
       Kamal       0.00      0.00      0.00         7
      Rajini       0.29      0.44      0.35         9
          SK       0.00      0.00      0.00         4
       Simbu       0.22      0.25      0.24         8
       Surya       0.00      0.00      0.00         4
         VJS       0.33      0.21      0.26        14
        Viay       0.10      0.17      0.12        12
      Vikram       0.50      0.13      0.21        15

    accuracy                           0.19        97
   macro avg       0.19      0.16      0.16        97
weighted avg       0.25      0.19      0.19        97

In [3]:
data = pd.read_csv('Instruments.csv')
 
data.head()

,Dialouge,f1,f2,f3,f4,f5,f6,f7,f8,f9,...,f43,f44,f45,f46,f47,f48,f49,f50,f51,Actor
0,D (1).wav,2505.561349,273291.6483,4163.362004,3.054404e+05,0.161794,0.008280,0.447468,0.082283,0.226600,...,71.55928,-4.091502,57.992065,-8.456772,86.727780,3.929301,66.566460,-11.872784,66.291570,D
1,D (2).wav,1096.192348,224106.2055,2257.020601,1.031782e+06,0.173143,0.007577,0.408799,0.093986,0.061763,...,170.18593,-17.189348,175.062230,2.250688,115.208916,6.286182,116.113976,-13.195838,141.524060,D
2,D (3).wav,1083.615779,67565.9715,2278.790611,4.364656e+05,0.153476,0.005305,0.304377,0.092197,0.055195,...,72.37702,-2.979644,110.593420,-6.668955,62.936066,4.282335,69.658380,-8.641368,72.684555,D
3,D (4).wav,1266.055658,116027.9056,2432.505137,5.473585e+05,0.141324,0.007071,0.296494,0.098430,0.075699,...,150.78856,-11.273940,200.842330,2.511643,139.577510,-0.271002,143.602720,-6.535358,180.258600,D
4,D (5).wav,1457.087789,153008.7634,2924.066616,4.743658e+05,0.129057,0.007672,0.371295,0.092815,0.096236,...,110.55477,-11.906658,77.335460,-1.391088,47.370050,4.239794,102.267740,-9.833932,75.485040,D

In [6]:
data.iloc[:,1:52]

,f1,f2,f3,f4,f5,f6,f7,f8,f9,f10,...,f42,f43,f44,f45,f46,f47,f48,f49,f50,f51
0,2505.561349,2.732916e+05,4163.362004,3.054404e+05,0.161794,0.008280,0.447468,0.082283,0.226600,0.004506,...,6.056866,71.559280,-4.091502,57.992065,-8.456772,86.727780,3.929301,66.566460,-11.872784,66.291570
1,1096.192348,2.241062e+05,2257.020601,1.031782e+06,0.173143,0.007577,0.408799,0.093986,0.061763,0.001392,...,8.652190,170.185930,-17.189348,175.062230,2.250688,115.208916,6.286182,116.113976,-13.195838,141.524060
2,1083.615779,6.756597e+04,2278.790611,4.364656e+05,0.153476,0.005305,0.304377,0.092197,0.055195,0.000284,...,8.448724,72.377020,-2.979644,110.593420,-6.668955,62.936066,4.282335,69.658380,-8.641368,72.684555
3,1266.055658,1.160279e+05,2432.505137,5.473585e+05,0.141324,0.007071,0.296494,0.098430,0.075699,0.000783,...,-0.621475,150.788560,-11.273940,200.842330,2.511643,139.577510,-0.271002,143.602720,-6.535358,180.258600
4,1457.087789,1.530088e+05,2924.066616,4.743658e+05,0.129057,0.007672,0.371295,0.092815,0.096236,0.001139,...,0.377417,110.554770,-11.906658,77.335460,-1.391088,47.370050,4.239794,102.267740,-9.833932,75.485040
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
479,1182.935443,2.317745e+05,1964.592932,1.057282e+06,0.123880,0.003015,0.295596,0.097982,0.068782,0.001369,...,-7.435227,72.249565,-9.910206,77.154810,1.874670,79.606610,-8.035752,71.462790,-10.966430,117.429370
480,2293.188902,2.748949e+06,4105.194847,6.356695e+06,0.023254,0.000299,0.428928,0.090319,0.153489,0.021056,...,-0.694917,56.742320,-4.604621,48.448480,7.552333,59.053980,-0.359588,51.443336,2.316856,48.800724
481,1385.109068,4.819166e+05,2719.514455,2.157373e+06,0.095196,0.004472,0.383802,0.090907,0.062152,0.001152,...,6.356282,34.512417,-3.948202,34.318222,3.231714,34.977530,-2.654429,32.624596,2.636745,31.005798
482,2327.459283,9.497725e+05,4831.481193,3.917101e+06,0.117423,0.007396,0.449727,0.090147,0.095359,0.005260,...,1.869994,96.669870,0.676956,164.770340,6.991657,190.731410,2.875445,167.884580,2.645018,103.708450
483,1686.149201,4.535609e+05,3247.773914,2.535312e+06,0.148802,0.006887,0.333957,0.095178,0.085556,0.001999,...,-0.636382,93.206720,-1.741987,94.224930,5.519679,107.299310,6.374283,101.836395,3.669828,80.014206

In [7]:
data['Actor']

0           D
1           D
2           D
3           D
4           D
        ...
479    Vikram
480    Vikram
481    Vikram
482    Vikram
483    Vikram
Name: Actor, Length: 484, dtype: object

In [14]:
knn.predict(data.iloc[5:10,1:52])

array(['D', 'D', 'D', 'Ajith', 'Ajith'], dtype=object)

In [19]:
data.iloc[0:1,1:52]

,f1,f2,f3,f4,f5,f6,f7,f8,f9,f10,...,f42,f43,f44,f45,f46,f47,f48,f49,f50,f51
0,2505.561349,273291.6483,4163.362004,305440.4314,0.161794,0.00828,0.447468,0.082283,0.2266,0.004506,...,6.056866,71.55928,-4.091502,57.992065,-8.456772,86.72778,3.929301,66.56646,-11.872784,66.29157

In [16]:
kmeans.predict(data.iloc[1:2,1:52])

NameError: name 'kmeans' is not defined